services:
  - type: web
    name: skyclock-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py  # Updated command
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
      - key: DATABASE_URL
        fromDatabase:
          name: skyclock-db
          property: connectionString
      - key: WEBHOOK_URL
        value: https://skyclock-bot.onrender.com
      - key: RENDER
        value: true